[server]
fileWatcherType = "none"
maxUploadSize = 5
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
